[general]
import = ["theme_active.toml", "keymaps.toml"]

[window]
padding.x = 12
padding.y = 10
startup_mode = "SimpleFullscreen" # macOS only, makes Alacritty start in fullscreen mode
decorations = "none"              # Removes the window decoration (title bar, etc.)
option_as_alt = "OnlyLeft"        # macOS only, make Option key behave as Alt
opacity = 0.75
blur = true

[font]
size = 14
# FiraCode Nerd Font
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Italic" }

[scrolling]
history = 0

[cursor.style]
shape = "Block"
blinking = "On"
