# Alias `Ctrl+-` to `Ctrl+Shift+-`
[[keyboard.bindings]]
key = "-"
mods = "Control"
# `\u001b[` (equals to `\x1b`) means escape, see https://en.wikipedia.org/wiki/ANSI_escape_code#CSIsection
# `95` means `_`, see ASCII Table
# `5u` means `Control`, see https://github.com/alacritty/alacritty/issues/2688#issuecomment-516613134
chars = "\u001b[95;5u"

# Use zellij to clear history
[[keyboard.bindings]]
key = "K"
mods = "Command"
action = "ReceiveChar"

# Use zellij to search history
[[keyboard.bindings]]
key = "F"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "switch-mode",
  "entersearch",
] }

# Zellij shortcuts

# Edit Scrollback
[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "edit-scrollback",
] }

# Manage Window(Session)/Tab
# [[keyboard.bindings]]
# key = "N"
# mods = "Command"
# action = "None"

[[keyboard.bindings]]
key = "T"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = ["ac", "new-tab"] }

[[keyboard.bindings]]
key = "W"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = ["ac", "close-tab"] }

[[keyboard.bindings]]
key = "["
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-previous-tab",
] }

[[keyboard.bindings]]
key = "]"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-next-tab",
] }

[[keyboard.bindings]]
key = "1"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "1",
] }

[[keyboard.bindings]]
key = "2"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "2",
] }

[[keyboard.bindings]]
key = "3"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "3",
] }

[[keyboard.bindings]]
key = "4"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "4",
] }

[[keyboard.bindings]]
key = "5"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "5",
] }

[[keyboard.bindings]]
key = "6"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "6",
] }

[[keyboard.bindings]]
key = "7"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "7",
] }

[[keyboard.bindings]]
key = "8"
mods = "Command"
command = { program = "/opt/homebrew/bin/zellij", args = [
  "ac",
  "go-to-tab",
  "8",
] }

[[keyboard.bindings]]
key = "9"
mods = "Command"
action = "None"
